export const questions = 
    
      [
        "Question 1",
        "Difficulty paying attention to details or at school, work or other\nmaking careless mistakes in activities",
        "Question 2",
        "Maintaining attention in tasks or chores that require attention\n    difficulty",
        "Question 3",
        "Difficulty listening when swimming face to face with someone",
        "Question 4",
        "Completing school homework or tasks given at work\ndifficulty following instructions given",
        "Question 5",
        "Difficulty organizing tasks and activities",
        "Question 6",
        "Avoiding tasks that require long mental effort reluctant to dislike",
        "Question 7",
        "Losing Items Required for Quests and events (for example:\nschool assignments, pencil, book…",
        "Question 8",
        "Easily distracted",
        "Question 9",
        "Forgetful in daily activities",
        "Question 10",
        "Fidgeting of Hands and Feet, inability to sit still",
        "Question 11",
        "Displacement in Sitting Situations",
        "Question 12",
        "Feeling Uneasy to Run Around",
        "Question 13",
        "Difficulty doing leisure activities quietly",
        "Question 14",
        "It\\'s as if the motor is attached to being constantly in motion act like",
        "Question 15",
        "Talking a lot",
        "Question 16",
        "Answer before the question is completed",
        "Question 17",
        "Difficulty in Queue Waiting",
        "Question 18",
        "Interfering in Others Business or Interrupting Their Conversation",
        "Question 19",
        "Not Achieving Goals and Feeling of Failure",
        "Question 20",
        "Inability to finish a job started or difficulty starting a job",
        "Question 21",
        "Dealing with many jobs/projects at the same time, keeping track of these works\nand difficulty completing",
        "Question 22",
        "Even if the time and place is not suitable, whatever comes to mind at that moment.\n propensity to says",
        "Question 23",
        "Frequent pursuit of great excitement",
        "Question 24",
        "Inability to tolerate boredom",
        "Question 25",
        "Not following the paths and rules followed by everyone",
        "Question 26",
        "Impatience, low frustration threshold",
        "Question 27",
        "Impulsivity (acting without thinking)",
        "Question 28",
        "Feeling insecure",
        "Question 29",
        "Frequent mood swings",
        "Question 30",
        "Flashing and reacting",
        "Question 31",
        "Low self-worth",
        "Question 32",
        "Tapping with fingers, swinging or tapping",
        "Question 33",
        "Change jobs frequently",
        "Question 34",
        "Hypersensitivity/intolerance to stress",
        "Question 35",
        "Difficulty adjusting the time",
        "Question 36",
        "Forgetfulness",
        "Question 37",
        "Verbal aggression",
        "Question 38",
        "Physical aggression",
        "Question 39",
        "Alcohol use",
        "Question 40",
        "Substance use",
        "Question 41",
        "Legal difficulties and problems",
        "Question 42",
        "Depression",
        "Question 43",
        "Do not engage in self-harming behavior",
        "Question 44",
        "Being nervous and nervous for no reason (anxiety)",
        "Question 45",
        "not enjoying one's job",
        "Question 46",
        "Feelings of disappointment and discouragement",
        "Question 47",
        "Long-standing feeling of unhappiness",
        "Question 48",
        "Failure to reach a level compatible with capacity"
      ]
export const answers = {
    "Never": 0,
    "Sometimes": 1,
    "VeryOften": 2,
    "Usually": 3
}